import React from 'react'
import { SectionLabel } from '../ui/SectionLabel'
import { ScrollReveal } from '../ui/TechnicalPanel'
import { useReducedMotion } from '../background/AmbientBackground'

// ─── TechnologySection ────────────────────────────────────────────────────────
// Attestcoin + Creditcoin section with ~15s settlement visualization
// ─────────────────────────────────────────────────────────────────────────────

export function TechnologySection() {
  const prefersReducedMotion = useReducedMotion()
  const [signalPhase, setSignalPhase] = React.useState<
    'idle' | 'generating' | 'attested' | 'settled' | 'protected'
  >('idle')
  const [signalPct, setSignalPct] = React.useState(0)

  React.useEffect(() => {
    if (prefersReducedMotion) return

    const run = () => {
      const phases: { phase: typeof signalPhase; pct: number; delay: number }[] = [
        { phase: 'idle',       pct: 0,   delay: 1000 },
        { phase: 'generating', pct: 25,  delay: 2500 },
        { phase: 'attested',   pct: 60,  delay: 6000 },
        { phase: 'settled',    pct: 85,  delay: 3000 },
        { phase: 'protected',  pct: 100, delay: 2000 },
        { phase: 'idle',       pct: 0,   delay: 3000 },
      ]

      let elapsed = 0
      phases.forEach(p => {
        setTimeout(() => {
          setSignalPhase(p.phase)
          setSignalPct(p.pct)
        }, elapsed)
        elapsed += p.delay
      })
      setTimeout(run, elapsed + 500)
    }
    run()
  }, [prefersReducedMotion])

  const phaseColor = {
    idle: '#3a3a34',
    generating: '#a8e063',
    attested: '#5be4c8',
    settled: '#5be4c8',
    protected: '#a8e063',
  }[signalPhase]

  return (
    <section id="technology" className="relative section-padding" aria-label="Technology">
      <div className="max-w-7xl mx-auto px-5 md:px-8">
        <ScrollReveal>
          <SectionLabel className="mb-6">Technology</SectionLabel>
          <h2 className="font-display text-display-lg font-bold text-aegis-white mb-4">
            Verified on-chain.
            <br />
            <span className="text-aegis-cyan">Settled in seconds.</span>
          </h2>
          <p className="text-aegis-off text-base max-w-xl leading-relaxed mb-16">
            Aegis uses Creditcoin's Attestcoin protocol to cryptographically verify
            cross-chain position state before executing any protection action.
          </p>
        </ScrollReveal>

        <div className="grid lg:grid-cols-2 gap-8 mb-12">
          {/* Attestcoin card */}
          <ScrollReveal delay={0}>
            <div className="rounded-lg overflow-hidden h-full" style={{ background: '#0d0d0a', border: '1px solid #242420' }}>
              <div className="px-5 py-4 border-b border-aegis-border flex items-center gap-3">
                <div className="w-8 h-8 rounded-sm flex items-center justify-center" style={{ background: 'rgba(91,228,200,0.1)', border: '1px solid rgba(91,228,200,0.2)' }}>
                  <VerifyIcon className="w-4 h-4" color="#5be4c8" />
                </div>
                <div>
                  <div className="font-mono text-xs font-bold text-aegis-white tracking-wider">ATTESTCOIN</div>
                  <div className="font-mono text-label-xs text-aegis-dim">Verification Layer</div>
                </div>
              </div>
              <div className="p-5">
                <p className="text-sm text-aegis-off leading-relaxed mb-5">
                  The Attestcoin smart contract (ASC) verifies cross-chain position state
                  using Merkle proofs and continuity proofs generated by the oracle worker via{' '}
                  <span className="font-mono text-aegis-cyan text-xs">@gluwa/usc-sdk</span>.
                </p>
                <div className="space-y-2.5">
                  {[
                    { fn: 'verifyPosition(...)', note: 'Submits proof to ASC for verification' },
                    { fn: 'Block Prover precompile', note: 'Cryptographic proof verification on CC3' },
                    { fn: 'Merkle + continuity proof', note: 'Generated by oracle worker' },
                  ].map(item => (
                    <div key={item.fn} className="flex items-start gap-3">
                      <span className="font-mono text-xs text-aegis-cyan shrink-0 mt-0.5">{item.fn}</span>
                      <span className="text-xs text-aegis-dim">{item.note}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </ScrollReveal>

          {/* Creditcoin card */}
          <ScrollReveal delay={80}>
            <div className="rounded-lg overflow-hidden h-full" style={{ background: '#0d0d0a', border: '1px solid #242420' }}>
              <div className="px-5 py-4 border-b border-aegis-border flex items-center gap-3">
                <div className="w-8 h-8 rounded-sm flex items-center justify-center" style={{ background: 'rgba(91,228,200,0.1)', border: '1px solid rgba(91,228,200,0.2)' }}>
                  <SettleIcon className="w-4 h-4" color="#5be4c8" />
                </div>
                <div>
                  <div className="font-mono text-xs font-bold text-aegis-white tracking-wider">CREDITCOIN</div>
                  <div className="font-mono text-label-xs text-aegis-dim">Settlement Layer</div>
                </div>
              </div>
              <div className="p-5">
                <p className="text-sm text-aegis-off leading-relaxed mb-5">
                  The Settlement Contract on CC3 testnet (chain ID: 102031) coordinates
                  protection execution after successful attestation. It calls Aave or Compound
                  repayment on the source chain.
                </p>
                <div className="space-y-2.5">
                  {[
                    { fn: 'protectPosition(...)', note: 'Execute protection after verification' },
                    { fn: 'setProtectionMode(...)', note: 'Configure user protection parameters' },
                    { fn: 'SAFE_THRESHOLD: 1.05', note: 'Minimum health factor for execution' },
                  ].map(item => (
                    <div key={item.fn} className="flex items-start gap-3">
                      <span className="font-mono text-xs text-aegis-cyan shrink-0 mt-0.5">{item.fn}</span>
                      <span className="text-xs text-aegis-dim">{item.note}</span>
                    </div>
                  ))}
                </div>
                <div className="mt-4 pt-3 border-t border-aegis-border/30">
                  <span className="font-mono text-label-xs text-aegis-muted">
                    RPC: rpc.cc3-testnet.creditcoin.network
                  </span>
                </div>
              </div>
            </div>
          </ScrollReveal>
        </div>

        {/* ~15s Settlement Visualization */}
        <ScrollReveal delay={120}>
          <div className="rounded-lg overflow-hidden" style={{ background: '#0a0a08', border: '1px solid #242420' }}>
            <div className="px-5 py-4 border-b border-aegis-border flex items-center justify-between">
              <span className="font-mono text-xs text-aegis-dim tracking-widest uppercase">
                Conceptual Settlement Flow
              </span>
              <span className="font-mono text-label-xs text-aegis-muted">Demo · Not a live transaction</span>
            </div>
            <div className="p-6 md:p-10">
              <div className="flex items-center justify-between gap-4 md:gap-8 mb-8">
                {['Position Data', 'Proof Generated', 'Attestcoin', '~15s', 'Creditcoin', 'Protected'].map((label, i) => {
                  const isActive = i <= Math.floor((signalPct / 100) * 5)
                  const isCurrent = i === Math.floor((signalPct / 100) * 5)
                  return (
                    <React.Fragment key={label}>
                      <div className="flex flex-col items-center gap-2 text-center">
                        <div
                          className="w-8 h-8 md:w-10 md:h-10 rounded-full flex items-center justify-center transition-all duration-700"
                          style={{
                            background: isActive ? `${phaseColor}15` : '#111110',
                            border: `1px solid ${isActive ? phaseColor : '#242420'}`,
                            boxShadow: isCurrent ? `0 0 16px ${phaseColor}30` : 'none',
                          }}
                        >
                          {isCurrent && !prefersReducedMotion ? (
                            <div className="w-2 h-2 rounded-full animate-pulse-slow" style={{ background: phaseColor }} />
                          ) : (
                            <div className="w-2 h-2 rounded-full" style={{ background: isActive ? phaseColor : '#242420' }} />
                          )}
                        </div>
                        <span
                          className="font-mono text-label-xs tracking-wide text-center hidden md:block transition-colors duration-700"
                          style={{ color: isActive ? phaseColor : '#3a3a34' }}
                        >
                          {label}
                        </span>
                      </div>
                      {i < 5 && (
                        <div
                          className="flex-1 h-px transition-all duration-700"
                          style={{ background: i < Math.floor((signalPct / 100) * 5) ? phaseColor : '#242420', opacity: 0.5 }}
                        />
                      )}
                    </React.Fragment>
                  )
                })}
              </div>

              {/* Progress bar */}
              <div className="relative h-1.5 bg-aegis-raised rounded-full overflow-hidden">
                <div
                  className="h-full rounded-full transition-all duration-700"
                  style={{ width: `${signalPct}%`, background: phaseColor, boxShadow: `0 0 8px ${phaseColor}50` }}
                />
              </div>

              <div className="mt-4 text-center">
                <span
                  className="font-mono text-sm font-semibold tracking-wider uppercase transition-colors duration-500"
                  style={{ color: phaseColor }}
                >
                  {signalPhase === 'idle' ? 'Standby — Monitoring Active' :
                   signalPhase === 'generating' ? 'Generating Merkle + Continuity Proof…' :
                   signalPhase === 'attested' ? 'Attestcoin Verification — ~15 seconds' :
                   signalPhase === 'settled' ? 'Settlement Contract Executing…' :
                   'Position Protected ✓'}
                </span>
              </div>
            </div>
          </div>
        </ScrollReveal>
      </div>
    </section>
  )
}

function VerifyIcon({ className, color }: { className?: string; color: string }) {
  return (
    <svg className={className} viewBox="0 0 16 16" fill="none" stroke={color} strokeWidth="1.5">
      <path d="M8 1.5 L13.5 3.5 L13.5 8.5 C13.5 11.5 10.5 13.5 8 14.5 C5.5 13.5 2.5 11.5 2.5 8.5 L2.5 3.5 Z" />
      <path d="M5.5 8 L7 9.5 L10.5 6" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
}

function SettleIcon({ className, color }: { className?: string; color: string }) {
  return (
    <svg className={className} viewBox="0 0 16 16" fill="none" stroke={color} strokeWidth="1.5">
      <circle cx="8" cy="8" r="5.5" />
      <polyline points="5,8 7.5,10.5 11,6" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
}
